### ISSUE TITLE
Alt+Left/Right move to next event AND change time

### ISSUE THREAD

**Issue by sarkipo** [Exmaralda-Org/exmaralda#185]
Alt+Left/Right **both** move to next event **and** change time of the right border

Application name :Partitur-Editor
Application version :1.6.1
Build time :20190305.1412

**Comment by berndmoos** [comment]
On which OS is this? Is it only when the cell is selected, but no cursor inside the event?

**Comment by sarkipo** [comment]
It's on Windows 7 Pro 64 bit.
Exactly, it happens when there is no cursor inside the event.
When the cursor is inside, the time border also changes (the cursor stays in the same event and place), although I'm not sure if it is intended. (Arrow keys without Alt would just move the cursor within the event).

**Comment by berndmoos** [comment]
Okay. The intended behaviour is that (Shift+) Alt+Left/Right changes interval boundaries while the cursor is INSIDE the event. I wasn't aware that the keystroke is also active and does two things at a time when the cell is only selected, not editing. I guess I'll have to somehow suppress the action which moves the selection. This is a bit tricky, because I have little control over the latter state. I'll look into it.

**Comment by sarkipo** [comment]
Understood, thanks!

**Comment by berndmoos** [comment]
Still open, still need to check, will do

**Comment by berndmoos** [comment]
Fixed it. Only took one line and two and a half years...
