### ISSUE TITLE
ISO/TEI --> EXB conversion

### ISSUE THREAD

**Issue by berndmoos** [Exmaralda-Org/exmaralda#215]
This is badly needed. It can't be done without information loss (e.g. tokenisation), and it is somewhat dependent on transcription conventions (e.g. transforming `<pause>` into a pure text representation). [folker2exmaralda ](https://github.com/Exmaralda-Org/exmaralda/blob/master/src/org/exmaralda/folker/data/folker2exmaralda.xsl)is a starting point, but need to additionaly take care of span annotations, both time and token based. Written upon his grave was "he tried to convert everything into everything".

**Comment by berndmoos** [comment]
First version consisting of a 4-step-XSL conversion. Tested on the entire FOLK corpus. One transformation of this kind takes about 25 seconds.

**Comment by berndmoos** [comment]
![image](https://user-images.githubusercontent.com/13796493/99993495-0ff6d880-2db8-11eb-9a1d-3b6b1128dec3.png)

**Comment by berndmoos** [comment]
To do, to check:

- `@type` attribute: assimilated etc.
- `<seg>`: boundary symbols for HIAT, SegCor

**Comment by berndmoos** [comment]
Could use a normalize.xsl as the 0th step which moves the document closer to ZuMult schema-validity

**Comment by hannahedeland** [comment]
- TIE_GLOBAL_NN in isotei2exmaralda only if such incident or pause in input
- what about the silly whitespace at the end of events? add to normalize?

**Comment by hannahedeland** [comment]
Some more things for later:
- normalize.xslt does weird things with namespaces
- removeTimepointsWithoutAbsolute.xsl removes all timepoints in not yet aligned legacy data transcripts (oh no)
- isotei2exmaralda.xsl inserts TIE_GLOBAL_NN everywhere

**Comment by hannahedeland** [comment]
More:
* normalize.xsl somehow duplicates `<seg>`s if there is PP with indents/whitespace around them (around `<w>` etc. is fine) - but who would ever do that...
* quotes as quotation marks in `<pc>`s aren't properly handled by detokenize.xsl, should at least have proper spacing when reimported if we don't use `<q>`
* and we don't want spaces after pauses before `<pc>` stuff
* and last but not least, token annotation in ISO/TEI gets messed up by augmentTimeline.xsl when there are `<anchor>`s in the `<seg>`s (i.e. overlaps) since not enough new token `<anchor>`s are created

**Comment by hannahedeland** [comment]
And more:
* we don't need an extra set of double brackets in the TIE_GLOBAL_NN

**Comment by hannahedeland** [comment]
closing this, happily moving away from "collective issues" ;)
