### ISSUE TITLE
reinstalling exmaralda on mac doesn't replace settings

### ISSUE THREAD

**Issue by anneferger** [Exmaralda-Org/exmaralda#81]
When the mac application is replaced with the new one on a mac (in this case el capitan), all the settings stay the same and aren't replaced by the default ones, what may cause problems.

Maybe I can make a how to on uninstalling on mac if you could tell me where these settings are stored?

**Comment by berndmoos** [comment]
The settings are meant to stay the same from one release to the next (because the user can be expected to stick to his former preferences). What kind of problems does this cause? Finding the place where MAC stores Java preferences can be tricky: http://stackoverflow.com/questions/675864/where-are-java-preferences-stored-on-mac-os-x. There is also a "Reset" button under "Edit > Preferences" which can be pressed in emergency cases...

**Comment by anneferger** [comment]
In the project that reported bug #73 the changes of the preview version worked only after the settings were resetted - but you're right, that can be done the easiest with reset preferences. Thanks
